page_impressum:                 # the identifier
    pattern:  /impressum        # the route
    defaults: { _controller:  dmoritz\StarWarsDb:Page:impressum }  # the controller + action
    requirements:
        _method:  GET           # restraints